language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1

before_script:
  - chmod a+x ./travis-build.sh
  - chmod a+x ./travis-test.sh
  - chmod a+x ./travis-pack.sh

script:
  - ./travis-build.sh
  - ./travis-test.sh
  - ./travis-pack.sh